title: Моя База Знаний и Инструментов
description: Персональная вики, заметки, проекты и утилиты.
theme: minima # Можешь выбрать другую тему или создать свою
# baseurl: "/repository-name" # Раскомментируй и укажи имя репозитория, если это не your-username.github.io
# url: "https://your-username.github.io" # Раскомментируй и укажи свой URL
