title: Моя База Знаний и Инструментов
description: Персональная вики, заметки, проекты и утилиты.
theme: minima # Можешь выбрать другую тему или создать свою
# baseurl: "/repository-name" # Раскомментируй и укажи имя репозитория, если это не your-username.github.io
# url: "https://your-username.github.io" # Раскомментируй и укажи свой URL
collections:
  tasks:            # Имя коллекции
    output: false   # Не создавать отдельные HTML-страницы для каждой задачи (мы покажем их списком)

github:
  repository_url: https://github.com/mrvi0/mrvi0.github.io # URL репозитория
  commit_message: "Update task" # Сообщение коммита при обновлении сайта
  source:
    branch: main