name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - '_includes/**'
      - '_layouts/**'
      - '_data/**'
      - 'assets/**'
      - '_config.yml'
      - 'index.html'
      - 'wiki/**'
      - 'projects/**'
      - 'utilities/**'
      - 'tasks/index.md'
      - 'changelog.md'
      - '!_tasks/**'
      - '!.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl ''
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Уведомление об УСПЕХЕ
  notify_success:
    runs-on: ubuntu-latest
    needs: deploy # Зависит от deploy
    if: success() # <<< Запускается только при успехе deploy
    steps:
      - name: Send Telegram message on success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ **mrvi0.github.io build Success**

            *Branch:* `${{ github.ref_name }}`
            *Commit:* [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            *Project:* [${{ github.repository }}](${{ github.repository }})
            *Actor:* `${{ github.actor }}`
            
            *Workflow log:*
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          format: markdown
          disable_web_page_preview: true

  # Уведомление об ОШИБКЕ
  notify_failure:
    runs-on: ubuntu-latest
    needs: [build, deploy] # <<< Зависит от build И deploy
    if: failure() # <<< Запускается только при ошибке В ЛЮБОМ из предыдущих jobs (build или deploy)
    steps:
      - name: Send Telegram message on failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ **mrvi0.github.io build failed**

            *Branch:* `${{ github.ref_name }}`
            *Commit:* [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            *Project:* [${{ github.repository }}](${{ github.repository }})
            *Actor:* `${{ github.actor }}`

            *Workflow log:*
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          format: markdown
          disable_web_page_preview: true